# Generated by Django 6.0.2 on 2026-02-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefamodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='tarefamodel',
            table=None,
        ),
    ]
