# Generated by Django 6.0.2 on 2026-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefamodel_options_alter_tarefamodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefamodel',
            old_name='concluida',
            new_name='completo',
        ),
    ]
