# Generated by Django 6.0.3 on 2026-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_rename_concluida_tarefamodel_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamodel',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
